name: Refresh README Timestamp

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  refresh-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

     - name: Update README timestamp
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          if grep -q "<!-- Last updated:" README.md; then
            # Mevcut invisible comment'ı yeni timestamp ile değiştir
            sed -i "s/<!-- Last updated:.*-->/<!-- Last updated: $TIMESTAMP -->/" README.md
          else
            # Eğer comment yoksa en başa ekle
            echo "<!-- Last updated: $TIMESTAMP -->" | cat - README.md > /tmp/README.tmp
            mv /tmp/README.tmp README.md
          fi

      - name: Commit updated README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README timestamp" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
        
